variables:
  TARGET_PLATFORM: 'linux/amd64'
  TAG_REGEX: '/^\d+\.\d+\.\d+$/'
  BUILD_TEST_STAGE: 'BUILD_TEST'
  CONTAINERIZE_STAGE: 'CONTAINERIZE'
  RETAG_STAGE: 'RETAG'
  DEPLOY_STAGE: 'DEPLOY'
  STAGE:
    description: 'Pipeline stages, BUILD_TEST, CONTAINERIZE, RETAG & DEPLOY. Select appropriately!'
    value: 'BUILD_TEST'
  PLATFORM_ENV:
    description: 'Platform environment, dev is default. For production use prod, only required for DEPLOY stage.'
    value: 'dev'

stages:
  - build
  - containerize
  - retag
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  stage: build
  image: node:21.6.1-alpine
  variables:
    CI: "false"
  script:
    - npm install
    - NODE_OPTIONS="--openssl-legacy-provider" npm run-script build
  artifacts:
    paths:
      - build/
  rules:
    - if: '$STAGE == $BUILD_TEST_STAGE || $STAGE == $CONTAINERIZE_STAGE'
      when: always

containerize:
  stage: containerize
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/docker/Dockerfile"
      --build-arg "TARGET_PLATFORM=${TARGET_PLATFORM}"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}-dev"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE == $CONTAINERIZE_STAGE'
      when: always

retag:
  stage: retag
  image:
    name: docker:20.10.16
    entrypoint: [ "" ]
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-dev
    - docker tag $CI_REGISTRY_IMAGE:dev $CI_REGISTRY_IMAGE:prod
    - docker push $CI_REGISTRY_IMAGE:prod
    - docker rmi $CI_REGISTRY_IMAGE:dev $CI_REGISTRY_IMAGE:prod
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE == $RETAG_STAGE'
      when: manual

deploy:
  stage: deploy
  image: alpine/k8s:1.32.0
  variables:
    K8S_CLUSTER_AGENT: gdp/ga4k:gcp-k8s-agent
    ENV_FILE: 'gcp-dev-env'
    NAMESPACE: 'intervene-dev'
  before_script:
    - |
      if [[ "$PLATFORM_ENV" == "prod" ]]; then
        export NAMESPACE="intervene-prod"
        export ENV_FILE="gcp-prod-env"
        export K8S_CLUSTER_AGENT="gdp/ga4k:gcp-prod-k8s-agent"
      fi
  script:
    - kubectl config get-contexts
    - kubectl config use-context $K8S_CLUSTER_AGENT
    - kubectl -n $NAMESPACE get pods
    - |
      helm upgrade --install geneticscores-frontend "./deployments" -f "./deployments/values-${ENV_FILE}.yaml" \
      --namespace "$NAMESPACE" \
      --set image.tag="$CI_COMMIT_TAG"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ $TAG_REGEX && $STAGE == $DEPLOY_STAGE'
      when: manual
